### ISSUE TITLE
rates (of decay) and lifetime should be positive in result output

### ISSUE THREAD

**Issue by jsnel** [glotaran/pyglotaran#1033]
Please motivate why the change is being made, where it is made in the code, why before it was not as it should have been, and why now the output is as it should be.

- [ ] Add note in changelog on change in output
- [ ] Add documentation on sign of rates and lifetimes in output
- [ ] Add comment in code, in PR #1022 or this issue on why the change is made where it is made. 

> Actually, let us please create an issue motivating why the change is being made, and why before it was not as it should be, and now it is as it should be.
_Originally posted by @jsnel in https://github.com/glotaran/pyglotaran/pull/1022#discussion_r835946565_

**Comment by jsnel** [comment]
As was pointed out by @ism200 in correspondence:

> I see an array lifetime under coordinates, but that appears to contain only the (negatives of the) lifetimes of the first megacomplex (see lifetimes.png)
> ![lifetimes](https://user-images.githubusercontent.com/3616369/160296007-2051dbd8-e0a9-4fe8-b612-c8660584f422.png)
> 
>

**Comment by jsnel** [comment]
If you could @ism200 , please review the fix located here:
https://github.com/joernweissenborn/pyglotaran/blob/bb7af4e83efd0247457a9a6beb5dacb79af5d6ad/glotaran/builtin/megacomplexes/decay/util.py#L300-L301
which I commented on here:
https://github.com/glotaran/pyglotaran/pull/1022/files#r835945160

**Comment by joernweissenborn** [comment]
@ism200 That is really just cosmetic so that rates and life times have the same sign as the parameters.

@jsnel Ithas been before with negative sign because nobody reviewed it and I use the rates from the actual  k matrix eigenvalues here, not the optimized parameters. The rates and lifetimes here have anyway nothing to do with the user input  k matrix, they are in component, not in species space, hence the eigenvalues.

**Comment by s-weigand** [comment]
For documentation @ism200 's review https://github.com/glotaran/pyglotaran/pull/1022#discussion_r836157167
