### ISSUE TITLE
♻️ Update result comparison standard from 0.4.1 to 0.5.1

### ISSUE THREAD

**Issue by jsnel** [glotaran/pyglotaran#1046]
As described in #1045 the gold standard should be upgraded so that it can be used to test functionality added in v0.5.0 when v0.6.0 comes out.

**Comment by s-weigand** [comment]
The upgrade to `0.5.1` results was done in [this commit](https://github.com/glotaran/pyglotaran-examples/commit/eb9b5f0b839d26e840ca2fc6f4dd62abb914daa3).
The fix for the label degradation bug (#1042) was added [in this commit](https://github.com/glotaran/pyglotaran-examples/commit/22932485b4a6822364f89f851c1743ac6e57ad99)

@jsnel should we do a backport of #1043 and a `0.5.2` release?

**Comment by jsnel** [comment]
I guess you can either backport the fix and make a new patch release, or you need to add some more boilerplate in the result comparison action script. So whichever you prefer. If we do make a 0.5.2 release, include a copy of the 0.5.1 release notes, and add the reason for the patch at the top.

**Comment by jsnel** [comment]
Let's evaluate if this still makes sense @s-weigand , if so, let's do it alongside the v0.7.0 release, otherwise we close the issue.

**Comment by s-weigand** [comment]
The [current compare](https://github.com/glotaran/pyglotaran-examples/commit/0df6261dc10cdefbb90d22e76991bd3bbfe627ec) results use 0.7.0.dev0, so would say lets focus on the `0.7.0` release instead of doing a backport.
