### ISSUE TITLE
🐛 pyglotaran==0.7.2 doesnt work with xarray==2024.7.0

### ISSUE THREAD

**Issue by anmolbhatia05** [glotaran/pyglotaran#1509]
### Version information

- pyglotaran version: 0.7.2
- Python version: 3.10.14
- Operating System: macOS

### Describe the bug
When I try to run any pyglotaran based notebook in this zip package [2024PPPpyglotaran_files.zip](https://github.com/user-attachments/files/16582124/2024PPPpyglotaran_files.zip), I get the following error log [error_log.txt](https://github.com/user-attachments/files/16582113/error_log.txt). 

When installing the requirements for pyglotaran, xarray==2024.7.0 is downloaded which causes this issue. Pinning to any version less than it makes it work. 

### To Reproduce

1. Run '...'

```python
from glotaran import ...
```

1. See error

**Comment by s-weigand** [comment]
Thanks for raising this issue.
This was [already fixed on `main`](https://github.com/glotaran/pyglotaran/commit/7ca64ae0e5c936df6e27532a3e70586ee8a9ab18) when it still was a deprecation warning from `xarray==2024.5.0`.
So the next release will fix it.
@jsnel Since we planned to make the next release soonish (this weekend hopefully? 😅), I don't think we need a `0.7.2` post release.

**Comment by jsnel** [comment]
A new release was created yesterday which fixes this issue for all user. Get it while its hot, release details here:
https://github.com/glotaran/pyglotaran/releases/tag/v0.7.3
