### ISSUE TITLE
Rename glotaran repository pyglotaran

### ISSUE THREAD

**Issue by jsnel** [glotaran/pyglotaran#178]
Note that this rename requires changing the (builder, packaging, CI) services etc, so it needs to be done carefully. 

First order of business, analyze all services dependent on the name of the repository.

**Comment by s-weigand** [comment]
I compleatly agree with @jsnel, changing the name is not as trivial as it might seem on first glance.
IMO It would best to gather all changes which need to be made first and than have a coordinated change.
Things that will change, I can tell you right away:
* all absolute imports need to be changed `from glotaran.module import xyz`
* all the links for the badges will change
* the `config.py` for the docs aswell as all guides in the docs need to be changed 
* my ["sphinx hack"](https://github.com/glotaran/glotaran/blob/ceaa361077ef1ce8e2a293776c302486861f24ed/docs/generate_api_documentation.py#L240) for the api documentation needs to be changed
* the repo needs to be reactived in the CI's, coveralls and maybe pyup
* the encrypted PyPi passwords in the CI configs need to be changed, since the repo name was used for encryption
* before changing the name there should be a release on PyPi with a new readme, telling people that the project was renamed and where it can be found

**Comment by jsnel** [comment]
The package has been renamed on pypi from https://pypi.org/project/glotaran/ to https://pypi.org/project/pyglotaran/
