### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by joernweissenborn** [glotaran/pyglotaran#2]
We need to develop a complete API for the core, which can be used in python applications/notebooks.

The API will be built automatically out of docstrings and made available through [pyglotaran.readthedocs.io](https://pyglotaran.readthedocs.io/en/latest/user_documentation/api/glotaran.html#module-glotaran)

A complete API requires complete documentation.

**Comment by jsnel** [comment]
Although there's always room for improvement since the first officially released version of pyglotaran API documentation is present via read the docs. So I consider this issue completed. 

When the API documentation is found to be incomplete, unclear or wrong separate issues can be filed for this. 

Links to documentation:
- [v0.3 API Documentation](https://pyglotaran.readthedocs.io/en/v0.3.3/user_documentation/api_documentation.html)
- [v0.4 API Documentation](https://pyglotaran.readthedocs.io/en/v0.4.0/user_documentation/api_documentation.html) 
- [latest (main branch) API Documentation](https://pyglotaran.readthedocs.io/en/latest/api_documentation.html)
