### ISSUE TITLE
✨ Reference convolution implementation (measured IRF)

### ISSUE THREAD

**Issue by jsnel** [glotaran/pyglotaran#221]
See also issue #53 

In addition to the preferred analytical representations of the instrument response function (IRF), it should also be possible to use a so-called reference convolution algorithm, e.g. when said analytical representation is not available. 

![reference_convolution_ref_10 1371_journal pone 0070687](https://user-images.githubusercontent.com/3616369/67723518-9b970d80-f9dc-11e9-8275-0bb69cacc244.png)
Refer to [Warren et. al.](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0070687) for a more extensive description.

closes: #469

**Comment by jsnel** [comment]
From @SerLap's [publication](https://library.wur.nl/WebQuery/wurpubs/fulltext/54474):

The analysis of FLIM data typically employs a measured IRF g(t) in fitting the exponential decay model contained in Equation 3. Evaluation of Equation 3 requires the numerical convolution of g(t) with an exponential decay. Methods to perform this convolution have been addressed in the literature at least since the seminal paper of Grinvald and Steinberg (1974), as Bajzer et al. (1995) discuss. 

For FLIM data (in which g(t) and the exponential decay are very often represented by 256 or less time points), we have found that methods based on a Fourier transformation are problematic, and that iterative methods give better results. Since an iterative method for the convolution of a vector and an exponential decay was not found by the authors implemented in R or in openly available scientific programming libraries, a method based on an iterative technique suggested in Grinvald and Steinberg (1974) was implemented in the shared C library used by TIMP, as the function [Conv1](https://github.com/glotaran/TIMP/blob/master/pkg/src/ntr.c#L314).

**Comment by jsnel** [comment]
Some literature references found in a offline version of the TIMP ntr.c file:

- Bouchy M, Jezequel JY, Andre JC, Bordet J. Problems arising from the quantization of the data in the mathematical treatment of single photon counting experiments, deconvolution and reconvolution of analytical signals. Application to Fluorescence Spectroscopy, E.N.S.I.C.-I.N.P.L., Nancy, France. 1982;393–409.  (`ConvSimpleAlg`)
This publication is also referenced in @ism200's lecture notes. See this publication for more information: [Update (v1.2) to DLTPulseGenerator: A library for the simulation of lifetime spectra based on detector-output pulses](https://www.sciencedirect.com/science/article/pii/S2352711018301092)

**Comment by SerLap** [comment]
FLIM data with 256 channels don't really need anything but simple gaussian for convolution, as there is not enough time resolution, that is what we found out after we wrote those papers :) also from the practical point of view. However, now the FLIM systems become MUCH faster than 10 years ago so I think we can expect experiments where propper irf would be important. Thow those more for biophysical applications not for biology, in biology usually u don't really need that precise estimation. 
There are 3 implementations of the convolution in TIMP: 
1 would convolve 2 vectors but it has n^2 complexity, n number of channels, but it doesn't depend on the models,
2 would convolve measured IRF with a single exponential function.   complexity m*n, m number of exponentials, n number of channels
3 is a reference convolution where u take into account the decay time of your reference component, just extension of convolution 2. So still per run u convolve your vector to a single exponential function.   
I dont remember which one is wich in TIMP.
we can also implement an extension of convolution 1 to use a reference component instead of scatter. 

Convolution 1 is just an implementation of a convolution formula for 2 discreet functions and can be happily replaced by any other implementation. Convolution 2 and 3 are much faster and is an implementation of the  algorithm in the 

M.Bouchy,J.Y.Jezequel,J.C.Andre,J.Bordet,Problems arising from the quantization
of the data in the mathematical treatment of single photon counting experiments. In:
Deconvolution and reconvolution of analytical signals. Application to ?uorescence
spectroscopy,E.N.S.I.C.-I.N.P.L., Nancy, France, 1982, pp. 393-409

Ivo should have a paper version of that paper.

**Comment by ism200** [comment]
dear all,

in my opinion the multiple gaussian is the most flexible, but it needs 
to be used with care.

the Bouchy et al is here

https://www.nat.vu.nl/~ivo/pub_rest/Bouchy

kind regards,

ivo

Ivo van Stokkum
programme director MSc Physics and Astronomy JD
chair Works Council Faculty of Science
Department of Physics and Astronomy
Faculty of Science
Vrije Universiteit Amsterdam
De Boelelaan 1081
1081 HV Amsterdam
The Netherlands
tel: +31 205987868
fax: +31 205987992
E-mail: i.h.m.van.stokkum@vu.nl
Room: T.1.12
http://www.nat.vu.nl/~ivo/

**Comment by SerLap** [comment]
I agree with Ivo, that multiple gaussian is the best to use when possible,

**Comment by jsnel** [comment]
Reference attached: [Uploading M_Bouchy_et_al-Problem_arising_from_the_quantization_of_the_data_in_the_Mathematical_threatment_of_single_photon_counting_experiments.pdf…]()
