### ISSUE TITLE
Improvement to CODEOWNERS sanity workflow

### ISSUE THREAD

**Issue by jsnel** [glotaran/pyglotaran#506]
The sanity workflow can be triggered manually using workflow_dispatch but as per suggestion of @s-weigand "it might also be good to run it on `push` and/or `pull_request` in case the `CODEOWNERS` file gets changed e.g. if we add a new subpackage with specific owners.
Since the workflow isn't coupled to other steps and should be pretty quick this shouldn't produce a big overhead."

_Originally posted by @s-weigand in https://github.com/glotaran/pyglotaran/pull/500#discussion_r559195208_

**Comment by s-weigand** [comment]
#508 will make the workflow run on `push`, but only for the main repo since it depends on `secrets.OWNERS_VALIDATOR_GITHUB_SECRET` which only exists in the glotaran organization.

For it to run on pull requests, we would need to use `pull_request_target` as trigger, which is `pull_request` with elevated rights, so it has access to the token. But since `pull_request_target` atm has a security vulnerability we should wait for that issue to be resolved first.

With the workflow being run on `push` we at least get an error as soon as the merge happened.

**Comment by s-weigand** [comment]
`pull_request_target` security issue
As Video:

[![pull_request_target issue](http://img.youtube.com/vi/_fpXyS_i1xE/0.jpg)](https://www.youtube.com/watch?v=_fpXyS_i1xE)

[Githubs statement](https://securitylab.github.com/research/github-actions-preventing-pwn-requests)

**Comment by jsnel** [comment]
What action do we (still) need to take (if any)? Or can this issue be marked as resolved and closed?

**Comment by s-weigand** [comment]
I will have a closer look at making the workflow run for PR's next week since `pull_request_target` only appears to cause security issues in combination with `explicit checkout`.

**Comment by s-weigand** [comment]
Better late than never, I did finally [read up on `pull_request_target` and potential security issues](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/).
To use it we need to explicitly check out the PR, which is a big NoNo EXCEPT:

>  Having said that, mixing pull_request_target with an explicit PR checkout is not always vulnerable. The workflow may, for example:
>  - Reformat and commit the code
>  - Checkout both base and head repositories and generate a diff
>  - Run grep on the checked out source.

This is exactly our use case since the potentially dangerous is never run but only linted.

Since we all work from forks by now, I would restrict the `push` trigger to the `main` branch so dependabot doesn't fail and use `pull_request_target` with explicit checkouts to check PRs.
