### ISSUE TITLE
Update community profile

### ISSUE THREAD

**Issue by jsnel** [glotaran/pyglotaran#608]
The [community profile](https://docs.github.com/en/github/building-a-strong-community/about-community-profiles-for-public-repositories) for [pyglotaran ](https://github.com/glotaran/pyglotaran/community) is not complete. 

[Overview here](https://github.com/glotaran/pyglotaran/community):

- [x]  Description
- [x]  README
- [x]  Code of conduct
- [x]  Contributing
- [x]  License
- [x]  Issue templates
- [x]  Pull request template
- [ ]  Repository admins accept content reports

**Comment by s-weigand** [comment]
For `Code of conduct` I normally just go with the default `Contributor Covenant Code of Conduct` GitHub provides.

We have ` Issue templates` but GitHub expects them in `.github/ISSUE_TEMPLATE` rather than `.github`, thus it complains.
Maybe we want to differentiate between bug reports and feature requests.

`Repository admins accept content reports` I see for the first time since it is an orga only setting, but enabling it should be fine ([see](https://docs.github.com/en/communities/moderating-comments-and-conversations/managing-reported-content-in-your-organizations-repository)).

**Comment by s-weigand** [comment]
`Code of conduct` is done via [`.github` orga repo](https://github.com/glotaran/.github)
