### ISSUE TITLE
🐛 CLI is not throwing deprecation warnings

### ISSUE THREAD

**Issue by jsnel** [glotaran/pyglotaran#771]
### Version information

- pyglotaran version: staging

### Describe the bug

Despite importing deprecating functions no deprecations method are shown
```
from glotaran.project.scheme import Scheme
from glotaran import read_model_from_yaml_file
```

### To Reproduce

Run test_cli on the fix/cli0.5 branch

**Comment by s-weigand** [comment]
Thinking about it a bit more only warnings for changed modules/packages get thrown at import time.
For functions and objects, the warnings will be thrown at call time.

I guess the `cli` needs more extensive testing.

And here are also my two cents on the issue:
The other question is if we want the CLI in the core or just make it a different package and add it as an extra (e.g. install as `pip install pyglotaran[cli]`). For some1 that only uses `pyglotaran` as a library (e.g. in notebooks) the CLI doesn't provide extra value + dealing with CLI/UI issues shouldn't clutter issues with the main fitting code.

**Comment by s-weigand** [comment]
I found the cause of the issue in the [python docs](https://docs.python.org/3/library/warnings.html#default-warning-filter).
Basically python filters all deprecation warnings which weren't directly caused by the code executed in the file itself.

This behavior can be changed by settings [PYTHONWARNINGS=always](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONWARNINGS).

Reproduce:
checkout `151dd810a241b2968106a9ac2d397edbe66b9135` on the fix/cli0.5 branch and run:
```console
$ PYTHONWARNINGS=always glotaran validate -p parameters.yml -m model.yml scheme.yml
```
In a unix like shell (`bash` / `gitbash`), this will show the deprecation warning.

```console
$ PYTHONWARNINGS=always glotaran validate -p parameters.yml -m model.yml scheme.yml
C:\Anaconda3\envs\pyglotaran\lib\site-packages\win32\lib\pywintypes.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp, sys, os
d:\git\pyglotaran\glotaran\cli\commands\util.py:51: DeprecationWarning: Usage of 'glotaran.analysis.sc

heme.Scheme' was deprecated, use 'glotaran.project.scheme.Scheme' instead.
This usage will be an error in version: '0.6.0'.
  return _load_file(filename, gta.analysis.scheme.Scheme.from_yaml_file, "scheme", verbose)
Loading scheme file 'scheme.yml'... d:\git\pyglotaran\glotaran\cli\commands\util.py:37: DeprecationWar

ning: Usage of 'glotaran.project.scheme.Scheme.from_yaml_file(filename)' was deprecated, use 'glotaran

.io.load_scheme(filename)' instead.
This usage will be an error in version: '0.6.0'.
  result = loader(filename)
Success
Your model is valid.
```

So in the CLI tests, we should pass that env var to the [`ClickRunner`](https://click.palletsprojects.com/en/8.0.x/api/#click.testing.CliRunner) and check the output for deprecation warnings caused by glotaran. This also means that we need better tests coverage for the CLI (Ref: https://github.com/glotaran/pyglotaran/issues/675)

Side Note:
This will only work if you use valid files because the CLI will exit early on errors.
So you need to find a `scheme.yml` on your system first since (if you aren't working with the CLI) it only gets generated by the test for `yml` save_result. Luckily `pytest` keeps the temp files for the last 3 runs around.

**Comment by s-weigand** [comment]
#775 made this a whole lot easier.
Now we should just need to check if `GlotaranApiDeprecationWarning` is in the output.

**Comment by s-weigand** [comment]
@joernweissenborn Since you are the only one of us using `pyglotaran` with the CLI, could you please confirm that it now shows the warnings?

**Comment by joernweissenborn** [comment]
confirm

**Comment by s-weigand** [comment]
@joernweissenborn Thanks for confirming, now this can be closed 🎉
