### ISSUE TITLE
🐛 Inconsistent use of initial_concentration normalization w.r.t a_matrix calculation

### ISSUE THREAD

**Issue by jsnel** [glotaran/pyglotaran#932]
# Inconsistent use of initial_concentration normalization w.r.t a_matrix calculation

This issue is a semi-duplicate of #926, but digs a little deeper and makes the link to PR #860 which first brought the issue to light.

The PR #927 may be expanded to resolve both #926 and this issue.

## Description

During the result comparison check running against PR #860 the PR that will introduce simple megacomplex (decay) models, [it was found](https://github.com/glotaran/pyglotaran/pull/860#issuecomment-985467588) there's a significant discrpancy with previous results, due to a bug fix (this issue) in result creation.

It was found that the a_matrix calculated while optimizing, is different from the a_matrix calculated when calculating the final results. During optimization the call to the a_matrix calculation method uses a (previously normalized) initial_concentrations, wheras during result creation the a_matrix calculation method uses the not normalized initial_concentrations.

In code, during optimization:
```python
initial_concentration = dataset_model.initial_concentration.normalized()
# <snip>
matrix = matrix @ k_matrix.a_matrix(initial_concentration)
```
versus in result creation:
```python
a_matrix = k_matrix.a_matrix(dataset_model.initial_concentration)
```

The a_matrix is later used in the calculation of the decay associated spectra, propagating differences.

```python
das = dataset[f"species_associated_{name}"].sel(species=species).values @ a_matrix.T
```

So it makes sense that the saved results are different specifically for the stored a_matrix and the decay_associated_spectra.

However, before simply fixing the issue, some further investigation is warranted, because it may hint at some other underlying issues. -> @ism200 will have a look (next week)

### New unit tests

In general, this issue revealed that it is currently possible for what is essentially the same data/result differs from optimization and result creation/saving, not nessecarily because different functions are used, but because the arguments to tohse function calls may differ. This suggests new unit tests are needed to guard against this.

Check that the data saves as results are consistent with the results during optimization -> new unit tests are needed.

### Reflect on design choices calculation

Clearly there's an option to choose between calculation the a_matrix with or without normalization, do we make that choice internally or do we leave that choice to the user?

Whatever we choose, we should justify it (in documentation). Also there may be some exception to the (always normalize)  rule, described below.

### Check against theory
Check that the decay associated spectra resulting from optimization are consistent with theory. Specifically, compare DAS for:
- parallel all compartments input of 1
- sequential first compartment input of 1

These should be identical (see Ivo's lecture notes).

This may touch on the implementation details in PR #860.

For the new simple megacomplexes, for the parallel complex the exclude_from_normalize argument should by default be true, for all compartments, so that it doesn't get normalized (inputs should stay at 1). -> check this is the case, or make it so.

### Call stack for a_matrix calculation in optimization

```
calculate_matrix (pyglotaran\glotaran\builtin\megacomplexes\decay\decay_megacomplex.py:107)
calculate_matrix (pyglotaran\glotaran\analysis\util.py:65)
<listcomp> (pyglotaran\glotaran\analysis\optimization_group_calculator_linked.py:230)
calculate_group (pyglotaran\glotaran\analysis\optimization_group_calculator_linked.py:229)
<lambda> (pyglotaran\glotaran\analysis\optimization_group_calculator_linked.py:247)
calculate_index_dependent_matrices (pyglotaran\glotaran\analysis\optimization_group_calculator_linked.py:245)
calculate_matrices (pyglotaran\glotaran\analysis\optimization_group_calculator_linked.py:217)
reduced_matrices (pyglotaran\glotaran\analysis\optimization_group.py:152)
calculate_residual (pyglotaran\glotaran\analysis\optimization_group_calculator_linked.py:306)
weighted_residuals (pyglotaran\glotaran\analysis\optimization_group.py:176)
calculate_full_penalty (pyglotaran\glotaran\analysis\optimization_group_calculator_linked.py:526)
full_penalty (pyglotaran\glotaran\analysis\optimization_group.py:198)
<listcomp> (pyglotaran\glotaran\analysis\optimize.py:100)
_calculate_penalty (pyglotaran\glotaran\analysis\optimize.py:100)
optimize (pyglotaran\glotaran\analysis\optimize.py:52)
```

### Call stack for a_matrix calculation in result creation

```text
retrieve_decay_associated_data (pyglotaran\glotaran\builtin\megacomplexes\decay\util.py:170)
finalize_data (pyglotaran\glotaran\builtin\megacomplexes\decay\decay_megacomplex.py:141)
finalize_data (pyglotaran\glotaran\model\dataset_model.py:77)
create_result_data (pyglotaran\glotaran\analysis\optimization_group.py:331)
_create_result (pyglotaran\glotaran\analysis\optimize.py:137)
optimize (pyglotaran\glotaran\analysis\optimize.py:76)
```

**Comment by ism200** [comment]
Dear all,
By definition the DAS are the spectra associated with parallel exponential decays, where each compartment has unit input, i.e. initial_concentration equal to 1. Assuming the compartments are named d1, d2, d3, ..., thus, by definition, exclude_from_normalize: [d2,d3, ...]. This should be verified within the current pyglotaran as follows. Simulate two parallelly decaying compartments with noise level 10^-15, and analyse with the parallel scheme. This should result in DAS that are identical (i.e. rms difference within the noise level) to the spectra used in the simulation (check 1). Next analyse these same data with a sequential scheme, where the compartments are named s1, s2, with initial_concentration equal to 1 and 0. Then from the estimated EAS (or SAS) compute DAS2=EAS*t(Amatrix). Check 2 is that DAS2 should be identical to the DAS estimated with the parallel model.
Please implement this double test.

**Comment by s-weigand** [comment]
I propose to refactor `retrieve_decay_associated_data` to use the actual values we want to save as arguments instead of calculating them from the megacomplex itself and refactor `calculate_matrix` to have an argument `dataset: None | xr.Dataset = None`.
If we call `retrieve_decay_associated_data` inside of `calculate_matrix` we can reduce code duplication and ensure that we save the same values we used for the calculations.
In `retrieve_decay_associated_data` the megacomplex is only used to calculate the full K matrix:

https://github.com/glotaran/pyglotaran/blob/89046e0a95117d63336f5cdb637bf8acf52addb2/glotaran/builtin/megacomplexes/decay/util.py#L163

And to get its label in case of multiple megacomplexes:

https://github.com/glotaran/pyglotaran/blob/89046e0a95117d63336f5cdb637bf8acf52addb2/glotaran/builtin/megacomplexes/decay/util.py#L199-L205

Since both  `retrieve_decay_associated_data` and `calculate_matrix` have access to `dataset_model` the extra information calculated in `finalize_data` like `name` 

https://github.com/glotaran/pyglotaran/blob/89046e0a95117d63336f5cdb637bf8acf52addb2/glotaran/builtin/megacomplexes/decay/decay_megacomplex.py#L119-L120

or `multiple_complexes`
https://github.com/glotaran/pyglotaran/blob/89046e0a95117d63336f5cdb637bf8acf52addb2/glotaran/builtin/megacomplexes/decay/decay_megacomplex.py#L138-L140

could be calculated inside of `retrieve_decay_associated_data` or passed to  `calculate_matrix` via the `**kwargs`.

Another way to prevent discrepancies between used and reported values in the future would be to factor out the calculation of values we want to report and need in other calculations in a separate function we then can use in both places. This could also be combined with the above approach to call the "reporter function" inside of the "calculation function".

**Comment by ism200** [comment]
Sebastian, Joris and I have tested this. Actually the **normalization occurs already during the simulation**. Then, when we analyse with a parallel model and exclude_from_normalize: [d2], we find DAS that are half the size of the spectra used in the simulation, i.e. it means that the concentrations have been normalized (we started with simple decays of amplitude 1, convolved with an IRF).
Now, in the sequential analysis of the same simulated data, and initial_concentration equal to 1 of s1, we find the same reconstructed DAS as were estimated with the parallel model.  
Thus, when we want to have a "global analysis" we need to exclude_from_normalize: [d2, ...]

**Comment by joernweissenborn** [comment]
So I understand that that right now you have fitting simulation because the uses normalized inputs. We can easily add add a switch to to turn off normalization at all which you just do in the simulation.

@ism200 Why should the first concentration be special? in a parallel model I thought I can interchange the compartments without problem since they are independent?

**Comment by ism200** [comment]
Yes, it would be good to switch off normalization by default when doing a simulation.
Joris and I discussed to need for a log of the normalization settings, so that the user is aware.
it is just convenience to use exclude_from_normalize: [d2, ...]
if you prefer exclude_from_normalize: [d1,d2, ...] that will probably work as well.
